---
- name: Empty dlrnapi output (no jobs reported)
  ansible.builtin.fail:
    msg: "FAILURE: No successful jobs reported to DLRN API"
  when:
    - cifmw_dlrn_promote_hash_report_status_output | length == 0 or cifmw_dlrn_promote_hash_report_status_output == '[]'

- name: Check for promotion criteria
  when:
    - cifmw_dlrn_promote_hash_report_status_output | length > 0
    - cifmw_dlrn_promote_hash_report_status_output  != '[]'
  block:
    - name: Check for criteria file before copying
      ansible.builtin.stat:
        path: "{{ cifmw_dlrn_promote_criteria_file }}"
      register: criteria_file

    - name: Abort the role on missing criteria file
      when: not criteria_file.stat.exists
      ansible.builtin.fail:
        msg: "{{ cifmw_dlrn_promote_criteria_file }} does not exists."

    - name: Copy criteria file
      when: criteria_file.stat.exists
      ansible.builtin.copy:
        dest: "{{ cifmw_dlrn_promote_workspace }}/"
        src: "{{ cifmw_dlrn_promote_criteria_file }}"
        remote_src: true

    - name: Load criteria for promotion
      ansible.builtin.include_vars:
        file: "{{ cifmw_dlrn_promote_workspace }}/{{ cifmw_dlrn_promote_criteria_file | basename }}"
        name: "criteria"

    - name: Query to match promotion criteria
      ansible.builtin.include_tasks: query_criteria.yml
      loop: "{{ criteria[cifmw_dlrn_promote_promotion_target] }}"
      loop_control:
        loop_var: "cifmw_dlrn_promote_criteria_job"
